id: f79abcba24be4a26adf0fab35b5ade68
initial_creation_type: ocr
source_metadata:
  volumes:
    e32cbdeec06f4a95892f282ae59999c4:
      base_file: v077.txt
      image_group_id: I1PD95923
      title: རྣལ་འབྱོར་ལ་འཇུག་པ།
      total_pages: 1254
      volume_number: 78
