id: D419CA26B
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2021-11-12T08:59:27+00:00'
last_modified: '2022-05-29T08:43:40.513197+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    877c:
      image_group_id: I1PD95923
      title: རྣལ་འབྱོར་ལ་འཇུག་པ།
      total_pages: 1254
      order: 78
      base_file: 877c.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
